apps/api/src/app.module.ts, apps/api/src/unit/entity/unit.entity.ts, apps/api/src/unit/unit.controller.ts, apps/api/src/unit/unit.module.ts, apps/api/src/unit/unit.service.ts
- GET /carelocations returns all the units in from the DB
- Tested with Postman
- Created an ICU entry to test things out
=> [TBCM-22] Select Care Location Profile - Setup Api

apps/web/src/common/constants.ts, apps/web/src/common/request-method.ts, apps/web/src/components/CareLocationSelector.tsx, apps/web/src/components/Dropdown.tsx, apps/web/src/components/PlanningContent.tsx, apps/web/src/components/PlanningWrapper.tsx, apps/web/src/components/Radio.tsx, apps/web/src/components/generic/DropdownOptions.tsx, apps/web/src/components/planning/ActivitiesGap.tsx, apps/web/src/components/planning/CareActivitiesBundle.tsx, apps/web/src/components/planning/Occupation.tsx, apps/web/src/components/planning/Profile.tsx, apps/web/src/components/planning/Suggestions.tsx, apps/web/src/pages/_app.tsx, apps/web/src/services/carelocations.tsx, apps/web/src/services/index.ts, apps/web/src/services/useCareLocations.ts, apps/web/src/services/useHttp.ts, apps/web/src/styles/styles.ts
- Introduced a generic dropdown
- Introduced a temporary component (CareLocationSelector) that makes the GET call to the API and passes the data to the dropdown (probably could be moved to a form later?)
- API call retrieves actual data from the database (the Units table, make sure you have some added if you want to test it).
=> [TBCM-20] Select Specific Care Location Profile

apps/api/src/app.module.ts, apps/api/src/planning-session/entity/planning-session.entity.ts, apps/api/src/planning-session/planning-session.controller.ts, apps/api/src/planning-session/planning-session.module.ts, apps/api/src/planning-session/planning-session.service.ts, apps/web/src/common/request-method.ts, apps/web/src/components/PlanningWrapper.tsx, apps/web/src/services/usePlanningSession.ts
- Provided the initial DB and backend setup
- POST /sessions creates a Session entry that only has an UUID for now
- Provided frontend functionality as well
=> [TBCM-31] Profile - Create Sessions Api

apps/api/src/app.module.ts, apps/api/src/database/database.module.ts, apps/api/src/database/scripts/seed-service.ts, apps/api/src/entities/allowed-activities.entity.ts, apps/api/src/occupation/entity/occupation.entity.ts, apps/api/src/occupation/occupation.controller.ts, apps/api/src/occupation/occupation.module.ts, apps/api/src/occupation/occupation.service.ts
[TBCM-28](https://freshworks.atlassian.net/browse/TBCM-28)
- GET /occupations retrieves all the occupations available
- Tested with Postman
- Prerequisite for [TBCM-9](https://freshworks.atlassian.net/browse/TBCM-9)
=> [TBCM-28] Selecting Occupations- Fetch Occupations API

apps/web/src/common/constants.ts, apps/web/src/common/interfaces.ts, apps/web/src/components/IconContainer.tsx, apps/web/src/components/generic/TooltipIcon.tsx, apps/web/src/styles/globals.css
- Provided generic TooltipIcon component that has a tooltip pop up when hovered over.
- Provided data object with all the icon data to be used in the generic component (colour, text, etc.). Please see `constants.ts`
- Provided an `IconContainer` component to display all the current icon types (delete after the PR, testing purposes only).
To-do:
- The tooltip will go above the screen if the icon is at the very top of the screen. Maybe make it dynamically switch sides (go to left, right bottom) if it goes beyond the screen size (sounds like a later feature and not part of the MVP).
- Maybe provide some sizing options for the icons/tooltip, right now I picked arbitrary value that seem close to the mockup.
=> [TBCM-10] Icon Components

apps/web/src/common/constants.ts, apps/web/src/common/util.ts, apps/web/src/components/IconContainer.tsx, apps/web/src/components/OccupationItem.tsx, apps/web/src/components/RightSideBarActivities.tsx, apps/web/src/components/generic/Tag.tsx, apps/web/src/styles/globals.css, apps/web/tailwind.config.js
Now tags for care activities on Step 2 have appropriate colours according to the recent Figma update.
=> [TBCM-55] Update Tag Styles for Care Activities

apps/web/src/common/constants.ts
Removed the gray question mark.
=> [TBCM-58] Activities Gap - Question Mark Icons With Same Description

apps/web/src/components/ActivitiesGapLegend.tsx, apps/web/src/components/planning/ActivitiesGap.tsx, apps/web/src/styles/globals.css
On initial load open table legend.
Change text color
=> Tbcm 63 open legend onload

.github/workflows/deploy-dev.yml, .github/workflows/deploy-test.yml, Makefile, terraform/cloudfront.tf, terraform/db.tf
- Added domain configuration for dev/test 
- Added deploy scripts for dev/test
=> Tbcm 99 manage domains for application

apps/api/src/database/scripts/seed-service.ts, apps/api/src/entities/allowed-activities.entity.ts, apps/api/src/migration/1694721151975-uniquenessInAllowedActivity.ts, apps/api/src/planning-session/entity/planning-session.entity.ts, apps/api/src/planning-session/planning-session.service.ts, apps/web/src/components/ActivitiesGapLegend.tsx, apps/web/src/components/PageTitle.tsx, apps/web/src/components/PlanningWrapper.tsx, apps/web/src/components/generic/Card.tsx, apps/web/src/components/generic/Popover.tsx, apps/web/src/components/planning/ActivitiesGap.tsx, apps/web/src/components/planning/ActivitiesGap/OverviewCards.tsx, apps/web/src/styles/globals.css
Following CareActivity-Gap enhancements changes are included in this PR:
1. Changed space constrained Legend to a Popover
2. Added scroll to the main content to avoid weird white spaces
3. AllowedActivity seed fixes: No redundant allowed activities
4. Overview tabs added - UI/Web and API changes
=> [TBCM-108] Care activity gap enhancements

apps/api/src/care-activity/care-activity.service.ts
Improved way to fetch Care Bundles fetch by care location [no manual updates || pure database fetcj]
=> [CareLocation Changes] Much Cleaner Care Bundles fetch by care location

apps/web/src/components/Footer.tsx, apps/web/src/components/HeaderLanding.tsx, apps/web/src/components/UserDropdown.tsx, apps/web/src/components/generic/AppMenu.tsx, apps/web/src/components/generic/Card.tsx, apps/web/src/components/generic/Spinner.tsx, apps/web/src/pages/index.tsx, apps/web/src/styles/globals.css, apps/web/tailwind.config.js
[TBCM-113](https://eydscanada.atlassian.net/browse/TBCM-113)
Following UI changes are done as part of this PR:
* Landing Page UI upgrades [New UI]
* App Spinner changes
* Tailwind config purge change 
* Logout dropdown UI upgrade
**NOTE: Creating this PR against User-management branch for now, until that one is merged to develop.**
=> [TBCM-113] [Beautify UI / upgrades] Landing Page, config changes

apps/api/src/auth/auth.controller.ts, apps/api/src/common/ro/empty-response.ro.ts
Countering the following build error error:
=> countering workspace caveats adding empty response to fix Runtime.ImportModuleError error

apps/api/src/planning-session/guards/session.guard.ts, apps/api/src/planning-session/planning-session.controller.ts, apps/api/src/planning-session/planning-session.service.ts, apps/web/src/components/Modal.tsx, apps/web/src/components/planning/Profile.tsx
Following changes are included in this PR:
* API/Web changes including removal of care activities on care location change
* Session guard to only allow access of session related APIs by the person created the session
=> [TBCM-112] [Web] [API] remove care activities on location change + Session Guard

apps/api/src/auth/auth.controller.ts, apps/api/src/care-activity/entity/care-activity.entity.ts, apps/api/src/common/constants.ts, apps/api/src/database/scripts/seed-service.ts, apps/api/src/migration/1696447301667-updatedAppDataFrom29Sep2023.ts, apps/api/src/occupation/entity/occupation.entity.ts, apps/api/src/planning-session/planning-session.service.ts, apps/web/src/common/constants.ts, apps/web/src/components/IconContainer.tsx, apps/web/src/components/PlanningContent.tsx, apps/web/src/components/RightSideBarActivities.tsx, apps/web/src/components/planning/ActivitiesGap.tsx, apps/web/src/components/planning/ActivitiesGap/OverviewCards.tsx, apps/web/src/components/planning/CareActivitiesBundle.tsx, apps/web/src/components/planning/Occupation.tsx, apps/web/src/components/planning/Profile.tsx, apps/web/src/pages/index.tsx, packages/common/src/dto/save-profile.dto.ts, scripts/cleaned-careactivities-29Sept2023.csv, scripts/cleaned-occupations-29Sept2023.csv
- Demo updates
- Copy changes
- Migration / data changes
All changes with the new data. Also added new data to the code base.
=> [Demo updates] [Copy changes] [New data script changes]

apps/web/src/common/constants.ts, apps/web/src/components/ActivitiesGapLegend.tsx, apps/web/src/components/OccupationSelector.tsx, apps/web/src/components/PlanningContent.tsx, apps/web/src/components/planning/ActivitiesGap.tsx, apps/web/src/components/planning/Occupation.tsx, apps/web/src/services/usePlanningSession.ts
=> minor ui enhancements

apps/api/src/common/constants.ts, apps/api/src/common/convert-activity-gap-table-to-csv.ts, apps/api/src/database/scripts/seed-service.ts, apps/api/src/migration/1696529645524-updatePermissionsEnum.ts, apps/web/src/common/constants.ts, apps/web/src/components/LeftSideBarActivites.tsx, apps/web/src/components/OccupationSelector.tsx, apps/web/src/components/planning/ActivitiesGap.tsx, apps/web/src/components/planning/ActivitiesGap/OverviewCards.tsx, apps/web/src/services/usePlanningActivitiesGap.tsx
Please refer commit messages for multiple fixes.
=> [UI enhancements] 

.github/workflows/deploy-test.yml
TF state migration done.
This PR updates the TEST env deployment script to be triggered on tag push.
Ref file: deploy-dev.yml
=> [GH] update test deployment workflow

apps/web/src/common/constants.ts, apps/web/src/components/ActivitiesGapLegend.tsx, apps/web/src/components/HeaderLanding.tsx, apps/web/src/components/IconContainer.tsx, apps/web/src/components/generic/Popover.tsx, apps/web/src/components/planning/ActivitiesGap.tsx, apps/web/src/pages/_app.tsx, apps/web/src/pages/index.tsx, apps/web/src/styles/globals.css, apps/web/tailwind.config.js
JIRA link: [TBCM-116](https://eydscanada.atlassian.net/browse/TBCM-116)
Includes the following changes [High priority items only]:
- Text changes : Landing screen & Legend
- Legend Icon Color Changes to Blue
- Rename as "Team-based Care" instead of full TBCM
=> [TBCM-116] [High Priority items] copy & icon changes

apps/web/src/common/interfaces.ts, apps/web/src/components/ActivitiesGapLegend.tsx, apps/web/src/components/Button.tsx, apps/web/src/components/Table.tsx, apps/web/src/components/generic/Popover.tsx, apps/web/src/components/generic/TooltipIcon.tsx, apps/web/src/components/planning/ActivitiesGap.tsx
Following UI Fixes are included in this PR:
- Mapping Table Popovers position: Last columns getting cut :: Fix
- Mapping Table Popovers - enable on click to support accessibility {Hovers don’t work well with accessibility} :: fix
- Table Legend popover getting cut for smaller screen :: fix
=> [UI] Popover enhancements & bug fixes

apps/web/src/components/OccupationItem.tsx, apps/web/src/components/OccupationListDropdown.tsx, apps/web/src/components/OccupationSelector.tsx, apps/web/src/components/PageTitle.tsx, apps/web/src/components/UserDropdown.tsx, apps/web/src/components/generic/AppMenu.tsx, apps/web/src/components/planning/ActivitiesGap.tsx, apps/web/src/components/planning/Occupation.tsx, apps/web/src/components/planning/PlanningContext.tsx, apps/web/src/services/useOccupations.ts, apps/web/src/services/usePlanningActivitiesGap.tsx, apps/web/src/services/usePlanningContext.ts, apps/web/src/services/usePlanningOccupations.ts
This PR includes the occupation list component in the gap page.
---
=> [TBCM-97] occupation list dropdown component created for gap step

apps/api/src/app.controller.ts, packages/common/src/constants/index.ts, packages/common/src/constants/role.ts
This PR includes securing of admin related APIs
* /update-care-activities
* /update-occupation
=> [TBCM-114] secure admin apis

.github/workflows/deploy-prod.yml, .github/workflows/pr-check-tf.yml, terraform/app.tf, terraform/cloudfront.tf
This PR includes the following changes
-  prod setup - infra changes
- `pr-check-tf.yml` changes to run workflow dispatch with options to run for tf plan on demand for any environment
- `deploy-prod.yml` to deploy to prod when pushed  "prod" tag on main branch.
Next: Merge everything to main
=> Tbcm prod infra setup

apps/api/src/occupation/dto/find-occupations.dto.ts, apps/api/src/occupation/occupation.service.ts, apps/web/src/common/request-method.ts, apps/web/src/components/AppContext.tsx, apps/web/src/components/AppLayout.tsx, apps/web/src/components/Sidebar.tsx, apps/web/src/components/SidebarButton.tsx, apps/web/src/components/generic/SearchBar.tsx, apps/web/src/components/occupational-scope/list.tsx, apps/web/src/components/occupational-scope/search.tsx, apps/web/src/pages/_app.tsx, apps/web/src/pages/occupational-scope.tsx, apps/web/src/services/useOccupationsFind.ts, packages/common/src/constants/sortOrder.ts
This PR includes the following:
- [Occupational Scope page] Occupation search with following:
- occupation names
- occupation descriptions
- associated care activity names
- Also includes sidenav open/close state lift up to the app context
=> [TBCM-123] Occupation search with name, description, care activity names;  

apps/api/src/allowed-activity/allowed-activity.controller.ts, apps/api/src/allowed-activity/allowed-activity.module.ts, apps/api/src/allowed-activity/allowed-activity.service.ts, apps/api/src/allowed-activity/dto/get-allowed-activities-by-occupation.dto.ts, apps/api/src/allowed-activity/entity/allowed-activity.entity.ts, apps/api/src/allowed-activity/ro/get-allowed-activities-by-occupation.ro.ts, apps/api/src/app.module.ts, apps/api/src/common/constants.ts, apps/api/src/database/scripts/seed-service.ts, apps/api/src/planning-session/planning-session.service.ts, apps/web/src/common/interfaces.ts, apps/web/src/common/request-method.ts, apps/web/src/components/Disclosure.tsx, apps/web/src/components/FilterButton.tsx, apps/web/src/components/FilterButtonGroup.tsx, apps/web/src/components/SortButton.tsx, apps/web/src/components/occupational-scope/ScopeOfPracticeFilters.tsx, apps/web/src/components/occupational-scope/ScopeOfPracticeList.tsx, apps/web/src/components/occupational-scope/ScopeOfPracticeSearch.tsx, apps/web/src/components/occupational-scope/details.tsx, apps/web/src/components/occupational-scope/list.tsx, apps/web/src/components/occupational-scope/scopeOfPractice.tsx, apps/web/src/services/useActivitiesAllowedByOccupation.ts, packages/common/src/constants/index.ts, packages/common/src/constants/occupationsFindSortKeys.ts, packages/common/src/constants/permissions.ts, packages/common/src/constants/sortKeys.ts
This PR includes Occupational Scope details : Scope of Practice secion 
*  Pagination
* Searching
* Filtering
* Sorting
=> [TBCM-127] Added Occupational Scope details : Scope of Practice secion  - Pagination, Searching, Filtering, Sorting

apps/web/src/components/AppContext.tsx, apps/web/src/components/PlanningWrapper.tsx, apps/web/src/components/Sidebar.tsx, apps/web/src/components/SidebarButton.tsx, apps/web/src/components/Stepper.tsx, apps/web/src/components/UserDropdown.tsx, apps/web/src/components/generic/AppMenu.tsx, apps/web/src/components/planning/ActivitiesGap/OverviewCards.tsx, apps/web/src/services/useActivitiesAllowedByOccupation.ts, apps/web/src/services/useOccupationsFind.ts, apps/web/tailwind.config.js
This PR addresses the following bugs:
1. App menu click issue
2. TBCM-166
3. TBCM-156
4. Gap Page - Card changes
=> UAT Bug Fixes 

apps/api/src/care-activity/care-activity.controller.ts, apps/api/src/care-activity/care-activity.service.ts, apps/api/src/care-activity/dto/find-care-activities.dto.ts, apps/api/src/care-activity/entity/care-activity.entity.ts, apps/api/src/care-activity/ro/get-bundle.ro.ts, apps/api/src/common/constants.ts, apps/api/src/database/scripts/seed-service.ts, packages/common/src/constants/careActivityType.ts, packages/common/src/constants/clinicalType.ts, packages/common/src/constants/index.ts, packages/common/src/constants/sortKeys.ts, packages/common/src/ro/careActivity.ro.ts, packages/common/src/ro/index.ts
Backend portion of TBCM-161 :: Care Terminologies List
=> [TBCM-161] [BE] Care Terminologies - List

apps/web/src/common/constants.ts, apps/web/src/common/request-method.ts, apps/web/src/components/OccupationSelector.tsx, apps/web/src/components/care-terminologies/index.tsx, apps/web/src/components/care-terminologies/list.tsx, apps/web/src/components/care-terminologies/search.tsx, apps/web/src/components/occupational-scope/ScopeOfPracticeList.tsx, apps/web/src/pages/care-terminologies/[id].tsx, apps/web/src/pages/care-terminologies/index.tsx, apps/web/src/services/useCareActivitiesFind.ts, apps/web/src/styles/globals.css
Frontend portion of TBCM-161 :: Care Terminologies List
=> [TBCM-161] [FE] Care Terminologies - List

apps/web/src/components/FeedbackForm.tsx
Bug
https://eydscanada.atlassian.net/browse/TBCM-182
Submitting feedback throws error when there is more than one space in feedback text
=> [BugFix] [TBCM-182] Trim text before submit to align with BE validator

apps/web/src/common/constants.ts, apps/web/src/common/interfaces.ts, apps/web/src/components/generic/TooltipIcon.tsx, apps/web/src/components/occupational-scope/ScopeOfPracticeList.tsx, apps/web/src/components/planning/ActivitiesGap.tsx, apps/web/src/styles/globals.css
Changes:
1. Gap Matrix page: occupations shown on tooltip
2. Occupation details screen: Header frozen for Care Activities
3. Unnecessary auto capitalize on matrix
=> [TBCM-189] Ensuring occupation is visible when scrolling

apps/api/src/planning-session/planning-session.service.ts, apps/web/src/components/ExportButton.tsx
=> updated export excel to include informational message

apps/api/src/user/user.service.ts, apps/web/src/components/PageTitle.tsx, apps/web/src/components/user-management/search.tsx, apps/web/src/pages/user-management/index.tsx
=> [TBCM-253] search users

apps/api/src/care-activity/care-activity.controller.ts, apps/api/src/care-activity/care-activity.service.ts, apps/api/src/care-activity/entity/care-activity-search-term.entity.ts, apps/api/src/common/audit/audit.subscriber.ts, apps/api/src/common/base.entity.ts, apps/api/src/common/custom-base.entity.ts, apps/api/src/feedback/entities/feedback.entity.ts, apps/api/src/feedback/feedback.controller.ts, apps/api/src/feedback/feedback.service.ts, apps/api/src/migration/1714161063249-base-entity-created-updated-by-all-entities.ts, apps/api/src/planning-session/entity/planning-session.entity.ts, apps/api/src/planning-session/planning-session.controller.ts, apps/api/src/planning-session/planning-session.service.ts, apps/api/src/user/entities/user-preference.entity.ts, apps/api/src/user/entities/user.entity.ts, apps/api/src/user/user.controller.ts, apps/api/src/user/user.service.ts
1. Update ALL existing entities to have a new column created_by and updated_by [update if already exists]
2. Ensure existing data is taken care of for the following entities already leveraging createdBy
* User invites
* Care Search Term
* Feedback
* Planning session
=> [TBCM-306] All entities now have createdBy and updatedBy

apps/api/src/care-activity/care-activity.service.ts
Bug fix identified in Dev for TBCM-281
=> [TBCM-281] [Fix] CMS find left join instead of inner

apps/web/src/components/Alert.tsx, apps/web/src/components/FileUpload.tsx, apps/web/src/components/content-management/care-activities/bulk-upload-modal.tsx
Contains two features:
1. Ability to upload file
2. Interpret and validate for format and sizing error
Using https://eydscanada.atlassian.net/browse/TBCM-288
=> [TBCM-288] Upload file; File format and size error handling

Makefile, package.json, packages/accessibility/package.json
TBCM - renaming keycloak redirect uri for dev and test
=> TBCM - renaming keycloak redirect uri for dev and test

.gitignore, apps/api/src/allowed-activity/entity/allowed-activity.entity.ts, apps/api/src/auth/auth.guard.ts, apps/api/src/auth/jwt.service.ts, apps/api/src/common/logger.service.ts, apps/web/src/components/AppLayout.tsx, apps/web/src/components/Stepper.tsx, apps/web/src/components/occupational-scope/list.tsx
- Token refresh not working
- Error: Hydration failed because the initial UI does not match what was rendered on the server.
- Warning:  Each child in a list should have a unique "key" prop
- Warning: validateDOMNesting(...): <td> cannot appear as a child of <table>. Error Component Stack
- Return 401 error when token expires so that frontend tries to refresh token
- Delay rendering AppLayout to prevent hydration error
- Fix unique keys in Stepper
- Fix dom nesting warning
=> TBCM-325 fix refresh token error

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy-test.yml, Makefile
Add terraform setup to github actions
Changed region to make open-db tunnel to ca-central-1a
=> TBCM - Add terraform setup to github actions

apps/api/src/database/scripts/seed-service.ts, apps/web/src/common/constants.ts
- Fix column header in bulk upload
- Hide content management for production
=> capitalize column header

terraform/db.tf
Updating Aurora version for tf deployment.
=> Updating version for aurora
